image:  docker/compose:latest
services:
  - docker:dind

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - build-languagetool

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - export DOCKER_PATH=docker/dockerfile-builder
    - export REPO_NAME=$CI_REGISTRY_IMAGE/tmt-builder
    - export IMAGE_NAME=$REPO_NAME:$CI_COMMIT_REF_NAME
    # Copy GitLab environment variables files with credentials
    - cp ${TRANSIFEX_CFG} cfg/credentials/transifexrc
    - cp ${ZANATA_CFG} cfg/credentials/zanata.yaml
    - cp ${WEBLATE_CFG} cfg/credentials/weblate.yaml
    - cp ${CROWDIN_CFG} cfg/credentials/crowdin.yaml
    - docker build --no-cache --tag tmt-builder --tag $IMAGE_NAME . -f $DOCKER_PATH
    - docker push $IMAGE_NAME

build-languagetool:
  stage: build-languagetool
  script:
    - export DOCKER_PATH=docker/dockerfile-languagetool
    - export REPO_NAME=$CI_REGISTRY_IMAGE/tmt-languagetool
    - export IMAGE_NAME=$REPO_NAME:$CI_COMMIT_REF_NAME
    - docker build --tag tmt-languagetool --tag $IMAGE_NAME docker/ -f $DOCKER_PATH
    - docker push $IMAGE_NAME

