pology:
    - rules-dir: /usr/local/share/pology/lang/ca/rules/
    - posieve: python /usr/local/bin/posieve
    - header-fix: '{0} set-header -sfield:"Language:ca" -screate "{1}"'
    - command: '{0} --skip-obsolete --coloring-type=html check-rules {1} "{2}" > "{3}"'
    - rules:
        - false-friends.rules
        - iso_639.rules
        - iso_4217.rules
        - keys.rules
        - acronyms.rules
        - abbreviations.rules
        - gender-neutralization.rules
        - date-format.rules
        - punctuation.rules
        - terminology-sc.rules
        - tags.rules
        - quality/pology/custom-rules/gnome-documentation.rules

lt:
    # Server is defined in LT_SERVER environment variable
    - lt_output: output/quality
    - disabled-rules: WHITESPACE_RULE,UPPERCASE_SENTENCE_START,CAMI_DE,ESPAIS_QUE_FALTEN_PUNTUACIO,PUNT_FINAL,ESPAI_DARRERE_PUNTICOMA,VERBS_NOMSPROPIS,COMMA_PARENTHESIS_WHITESPACE,PUNTUACIO_INCORRECTA,Y_CONJUNCIO,ESPAI_DARRERE_DOSPUNTS,USA_COMA_DECIMALS,ESPAI_DESPRES_DE_PUNT,SPELLOUT_NUMBERS,I_O,CATALAN_WORD_REPEAT_BEGINNING_RULE,CA_REPEATEDWORDS
    - disabled-categories: REPETITIONS_STYLE
    - enabled-rules: EXIGEIX_PLURALS_S,PER_INFINITIU
    - command: 'curl --data "language=ca-ES" --data "enabledRules={0}" --data "disabledRules={1}" --data "disabledCategories={2}" --data-urlencode "text@{3}" {4} > "{5}" 2>/dev/null'
    - lt-html-dir: quality/lt
